# Generated by Django 4.0.6 on 2022-07-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empSalary',
            field=models.CharField(max_length=50),
        ),
    ]
